"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-27 14:43:05.163819
"""

from alembic import op
import sqlalchemy as sa
import app.models.types
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievements",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "criteria_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("icon_key", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_achievements")),
        sa.UniqueConstraint("code", name=op.f("uq_achievements_code")),
    )
    op.create_table(
        "source_files",
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column(
            "encryption_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retention_expiry", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_files")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_source_files_storage_key")),
    )
    op.create_index(op.f("ix_source_files_checksum"), "source_files", ["checksum"], unique=False)
    op.create_index(
        op.f("ix_source_files_retention_expiry"), "source_files", ["retention_expiry"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("authentication_subject", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("preferred_language", sa.String(length=8), nullable=False),
        sa.Column("content_language", sa.String(length=8), nullable=False),
        sa.Column("theme_preference", sa.String(length=10), nullable=False),
        sa.Column("daily_goal_questions", sa.Integer(), nullable=False),
        sa.Column("account_status", sa.String(length=20), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("authentication_subject", name=op.f("uq_users_authentication_subject")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "auth_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_auth_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
    )
    op.create_index(op.f("ix_auth_sessions_token_hash"), "auth_sessions", ["token_hash"], unique=True)
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "guest_sessions",
        sa.Column("secure_session_token_hash", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "consent_state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("preferred_language", sa.String(length=8), nullable=False),
        sa.Column("converted_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["converted_user_id"],
            ["users.id"],
            name=op.f("fk_guest_sessions_converted_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guest_sessions")),
    )
    op.create_index(op.f("ix_guest_sessions_expires_at"), "guest_sessions", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_guest_sessions_secure_session_token_hash"),
        "guest_sessions",
        ["secure_session_token_hash"],
        unique=True,
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_password_reset_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_password_reset_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"), "password_reset_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "books",
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("guest_session_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("title_source", sa.String(length=16), nullable=False),
        sa.Column("author", sa.String(length=500), nullable=True),
        sa.Column("original_language", sa.String(length=16), nullable=True),
        sa.Column("detected_language", sa.String(length=16), nullable=True),
        sa.Column("file_format", sa.String(length=10), nullable=False),
        sa.Column("source_file_id", sa.Uuid(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("processing_status", sa.String(length=32), nullable=False),
        sa.Column("learning_status", sa.String(length=32), nullable=False),
        sa.Column("extraction_quality", sa.Float(), nullable=True),
        sa.Column(
            "extraction_warnings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("chapter_count", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("structure_confidence", sa.Float(), nullable=True),
        sa.Column("processing_version", sa.String(length=32), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(owner_user_id IS NOT NULL) <> (guest_session_id IS NOT NULL)",
            name=op.f("ck_books_book_single_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["guest_session_id"],
            ["guest_sessions.id"],
            name=op.f("fk_books_guest_session_id_guest_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"], ["users.id"], name=op.f("fk_books_owner_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["source_files.id"],
            name=op.f("fk_books_source_file_id_source_files"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_books")),
    )
    op.create_index(op.f("ix_books_guest_session_id"), "books", ["guest_session_id"], unique=False)
    op.create_index("ix_books_owner_hash", "books", ["owner_user_id", "content_hash"], unique=False)
    op.create_index(op.f("ix_books_owner_user_id"), "books", ["owner_user_id"], unique=False)
    op.create_index(op.f("ix_books_processing_status"), "books", ["processing_status"], unique=False)
    op.create_table(
        "ai_executions",
        sa.Column("book_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("guest_session_id", sa.Uuid(), nullable=True),
        sa.Column("task_type", sa.String(length=40), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("input_token_count", sa.Integer(), nullable=False),
        sa.Column("output_token_count", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("failure_category", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_ai_executions_book_id_books"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["guest_session_id"],
            ["guest_sessions.id"],
            name=op.f("fk_ai_executions_guest_session_id_guest_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ai_executions_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_executions")),
    )
    op.create_index("ix_ai_exec_book", "ai_executions", ["book_id"], unique=False)
    op.create_index("ix_ai_exec_created", "ai_executions", ["created_at"], unique=False)
    op.create_table(
        "analytics_events",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("actor_pseudo_id", sa.String(length=32), nullable=True),
        sa.Column("book_id", sa.Uuid(), nullable=True),
        sa.Column(
            "properties",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_analytics_events_book_id_books"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analytics_events")),
    )
    op.create_index(
        op.f("ix_analytics_events_actor_pseudo_id"), "analytics_events", ["actor_pseudo_id"], unique=False
    )
    op.create_index("ix_analytics_name_time", "analytics_events", ["name", "created_at"], unique=False)
    op.create_table(
        "annotations",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("guest_session_id", sa.Uuid(), nullable=True),
        sa.Column("annotation_type", sa.String(length=16), nullable=False),
        sa.Column(
            "source_location",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("selected_text", sa.Text(), nullable=True),
        sa.Column("note_text", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=16), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "annotation_type IN ('highlight','bookmark','note')", name=op.f("ck_annotations_annotation_type")
        ),
        sa.CheckConstraint(
            "(owner_user_id IS NOT NULL) <> (guest_session_id IS NOT NULL)",
            name=op.f("ck_annotations_annotation_single_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_annotations_book_id_books"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["guest_session_id"],
            ["guest_sessions.id"],
            name=op.f("fk_annotations_guest_session_id_guest_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_annotations_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_annotations")),
    )
    op.create_index("ix_annotations_book", "annotations", ["book_id"], unique=False)
    op.create_table(
        "chapters",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column(
            "start_location",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "end_location",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("detection_method", sa.String(length=32), nullable=False),
        sa.Column("detection_confidence", sa.Float(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_chapters_book_id_books"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chapters")),
        sa.UniqueConstraint("book_id", "ordinal", name="uq_chapter_order"),
    )
    op.create_index(op.f("ix_chapters_book_id"), "chapters", ["book_id"], unique=False)
    op.create_table(
        "processing_jobs",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("job_type", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column(
            "params",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("safe_error_message", sa.Text(), nullable=True),
        sa.Column(
            "stage_timings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_processing_jobs_book_id_books"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_jobs")),
    )
    op.create_index("ix_jobs_book_type", "processing_jobs", ["book_id", "job_type"], unique=False)
    op.create_table(
        "user_achievements",
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("guest_session_id", sa.Uuid(), nullable=True),
        sa.Column("actor_key", sa.String(length=40), nullable=False),
        sa.Column("scope_key", sa.String(length=40), nullable=False),
        sa.Column("achievement_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=True),
        sa.Column("earned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(owner_user_id IS NOT NULL) <> (guest_session_id IS NOT NULL)",
            name=op.f("ck_user_achievements_user_achievement_single_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["achievements.id"],
            name=op.f("fk_user_achievements_achievement_id_achievements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_user_achievements_book_id_books"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["guest_session_id"],
            ["guest_sessions.id"],
            name=op.f("fk_user_achievements_guest_session_id_guest_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_user_achievements_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_achievements")),
        sa.UniqueConstraint("achievement_id", "actor_key", "scope_key", name="uq_user_achievement"),
    )
    op.create_index(
        op.f("ix_user_achievements_owner_user_id"), "user_achievements", ["owner_user_id"], unique=False
    )
    op.create_table(
        "document_chunks",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("chapter_id", sa.Uuid(), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column(
            "source_start_location",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "source_end_location",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.Column("page_label_start", sa.String(length=32), nullable=True),
        sa.Column("page_label_end", sa.String(length=32), nullable=True),
        sa.Column("section_title", sa.String(length=500), nullable=True),
        sa.Column("embedding", app.models.types.EmbeddingType(256), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("extraction_confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_document_chunks_book_id_books"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.id"],
            name=op.f("fk_document_chunks_chapter_id_chapters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint("book_id", "ordinal", name="uq_chunk_order"),
    )
    op.create_index("ix_chunks_book_chapter", "document_chunks", ["book_id", "chapter_id"], unique=False)
    op.create_table(
        "quiz_sessions",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("guest_session_id", sa.Uuid(), nullable=True),
        sa.Column("chapter_id", sa.Uuid(), nullable=True),
        sa.Column("session_type", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("question_count", sa.Integer(), nullable=False),
        sa.Column("answered_count", sa.Integer(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("status_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "session_type IN ('lesson','revision')", name=op.f("ck_quiz_sessions_session_type")
        ),
        sa.CheckConstraint(
            "(owner_user_id IS NOT NULL) <> (guest_session_id IS NOT NULL)",
            name=op.f("ck_quiz_sessions_quiz_single_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_quiz_sessions_book_id_books"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.id"],
            name=op.f("fk_quiz_sessions_chapter_id_chapters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["guest_session_id"],
            ["guest_sessions.id"],
            name=op.f("fk_quiz_sessions_guest_session_id_guest_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_quiz_sessions_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_sessions")),
    )
    op.create_index("ix_quiz_sessions_book", "quiz_sessions", ["book_id"], unique=False)
    op.create_table(
        "reading_states",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("guest_session_id", sa.Uuid(), nullable=True),
        sa.Column("actor_key", sa.String(length=40), nullable=False),
        sa.Column("last_view", sa.String(length=16), nullable=False),
        sa.Column("last_chapter_id", sa.Uuid(), nullable=True),
        sa.Column("last_depth", sa.String(length=16), nullable=False),
        sa.Column(
            "last_position",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "chapters_read",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(owner_user_id IS NOT NULL) <> (guest_session_id IS NOT NULL)",
            name=op.f("ck_reading_states_reading_single_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_reading_states_book_id_books"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["guest_session_id"],
            ["guest_sessions.id"],
            name=op.f("fk_reading_states_guest_session_id_guest_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["last_chapter_id"],
            ["chapters.id"],
            name=op.f("fk_reading_states_last_chapter_id_chapters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_reading_states_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reading_states")),
        sa.UniqueConstraint("book_id", "actor_key", name="uq_reading_state_actor"),
    )
    op.create_index(op.f("ix_reading_states_book_id"), "reading_states", ["book_id"], unique=False)
    op.create_table(
        "summaries",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("chapter_id", sa.Uuid(), nullable=True),
        sa.Column("scope", sa.String(length=10), nullable=False),
        sa.Column("depth", sa.String(length=16), nullable=False),
        sa.Column("output_language", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "content_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("content_version", sa.Integer(), nullable=False),
        sa.Column("model_provider", sa.String(length=40), nullable=True),
        sa.Column("model_name", sa.String(length=80), nullable=True),
        sa.Column("prompt_version", sa.String(length=40), nullable=True),
        sa.Column(
            "token_usage",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("estimated_cost", sa.Float(), nullable=False),
        sa.Column("generation_duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("safe_error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(scope = 'book' AND chapter_id IS NULL) OR (scope = 'chapter' AND chapter_id IS NOT NULL)",
            name=op.f("ck_summaries_summary_scope"),
        ),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_summaries_book_id_books"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"], ["chapters.id"], name=op.f("fk_summaries_chapter_id_chapters"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_summaries")),
    )
    op.create_index(
        "ix_summaries_lookup",
        "summaries",
        ["book_id", "chapter_id", "depth", "output_language"],
        unique=False,
    )
    op.create_table(
        "topics",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("chapter_id", sa.Uuid(), nullable=True),
        sa.Column("parent_topic_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "source_evidence_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("difficulty_estimate", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_topics_book_id_books"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"], ["chapters.id"], name=op.f("fk_topics_chapter_id_chapters"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_topic_id"],
            ["topics.id"],
            name=op.f("fk_topics_parent_topic_id_topics"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topics")),
    )
    op.create_index("ix_topics_book_chapter", "topics", ["book_id", "chapter_id"], unique=False)
    op.create_table(
        "evidence_references",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("chapter_id", sa.Uuid(), nullable=True),
        sa.Column("source_type", sa.String(length=10), nullable=False),
        sa.Column("page_label", sa.String(length=32), nullable=True),
        sa.Column("page_index", sa.Integer(), nullable=True),
        sa.Column("epub_location", sa.String(length=500), nullable=True),
        sa.Column("character_start", sa.Integer(), nullable=True),
        sa.Column("character_end", sa.Integer(), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("document_version", sa.String(length=64), nullable=False),
        sa.Column("extraction_confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_evidence_references_book_id_books"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.id"],
            name=op.f("fk_evidence_references_chapter_id_chapters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_evidence_references_chunk_id_document_chunks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_references")),
    )
    op.create_index("ix_evidence_book_chunk", "evidence_references", ["book_id", "chunk_id"], unique=False)
    op.create_table(
        "questions",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("chapter_id", sa.Uuid(), nullable=True),
        sa.Column("topic_id", sa.Uuid(), nullable=True),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("question_type", sa.String(length=16), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column(
            "options_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("correct_option_key", sa.String(length=1), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("misconception", sa.Text(), nullable=True),
        sa.Column(
            "evidence_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("generation_method", sa.String(length=16), nullable=False),
        sa.Column("validation_status", sa.String(length=16), nullable=False),
        sa.Column(
            "validation_report",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("semantic_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("embedding", app.models.types.EmbeddingType(256), nullable=True),
        sa.Column("prompt_version", sa.String(length=40), nullable=True),
        sa.Column("model_provider", sa.String(length=40), nullable=True),
        sa.Column("model_name", sa.String(length=80), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("correct_option_key IN ('A','B','C','D')", name=op.f("ck_questions_qcorrect_key")),
        sa.CheckConstraint(
            "question_type IN ('recall','comprehension','application','inference')",
            name=op.f("ck_questions_qtype"),
        ),
        sa.CheckConstraint("difficulty BETWEEN 1 AND 3", name=op.f("ck_questions_qdifficulty")),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_questions_book_id_books"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"], ["chapters.id"], name=op.f("fk_questions_chapter_id_chapters"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topics.id"], name=op.f("fk_questions_topic_id_topics"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
    )
    op.create_index(
        "ix_questions_bank",
        "questions",
        ["book_id", "chapter_id", "validation_status", "language"],
        unique=False,
    )
    op.create_index(
        "ix_questions_fingerprint", "questions", ["book_id", "semantic_fingerprint"], unique=False
    )
    op.create_table(
        "topic_mastery",
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("guest_session_id", sa.Uuid(), nullable=True),
        sa.Column("actor_key", sa.String(length=40), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("mastery_score", sa.Float(), nullable=False),
        sa.Column("confidence_level", sa.Float(), nullable=False),
        sa.Column("attempts_count", sa.Integer(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("review_interval_days", sa.Float(), nullable=False),
        sa.Column("last_practiced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(owner_user_id IS NOT NULL) <> (guest_session_id IS NOT NULL)",
            name=op.f("ck_topic_mastery_mastery_single_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_topic_mastery_book_id_books"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["guest_session_id"],
            ["guest_sessions.id"],
            name=op.f("fk_topic_mastery_guest_session_id_guest_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_topic_mastery_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topics.id"], name=op.f("fk_topic_mastery_topic_id_topics"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_mastery")),
        sa.UniqueConstraint("topic_id", "actor_key", name="uq_mastery_actor_topic"),
    )
    op.create_index("ix_mastery_book", "topic_mastery", ["book_id"], unique=False)
    op.create_table(
        "question_attempts",
        sa.Column("quiz_session_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("selected_option_key", sa.String(length=1), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("response_duration_ms", sa.Integer(), nullable=True),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_question_attempts_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["quiz_session_id"],
            ["quiz_sessions.id"],
            name=op.f("fk_question_attempts_quiz_session_id_quiz_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_attempts")),
        sa.UniqueConstraint("quiz_session_id", "question_id", "attempt_number", name="uq_attempt"),
    )
    op.create_index("ix_attempts_question", "question_attempts", ["question_id"], unique=False)
    op.create_index(
        op.f("ix_question_attempts_quiz_session_id"), "question_attempts", ["quiz_session_id"], unique=False
    )
    op.create_table(
        "session_questions",
        sa.Column("quiz_session_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("served_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_session_questions_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["quiz_session_id"],
            ["quiz_sessions.id"],
            name=op.f("fk_session_questions_quiz_session_id_quiz_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_questions")),
        sa.UniqueConstraint("quiz_session_id", "position", name="uq_session_position"),
        sa.UniqueConstraint("quiz_session_id", "question_id", name="uq_session_question"),
    )
    op.create_table(
        "summary_evidence",
        sa.Column("summary_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("section_key", sa.String(length=80), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence_references.id"],
            name=op.f("fk_summary_evidence_evidence_id_evidence_references"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["summary_id"],
            ["summaries.id"],
            name=op.f("fk_summary_evidence_summary_id_summaries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_summary_evidence")),
    )
    op.create_index(op.f("ix_summary_evidence_summary_id"), "summary_evidence", ["summary_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_summary_evidence_summary_id"), table_name="summary_evidence")
    op.drop_table("summary_evidence")
    op.drop_table("session_questions")
    op.drop_index(op.f("ix_question_attempts_quiz_session_id"), table_name="question_attempts")
    op.drop_index("ix_attempts_question", table_name="question_attempts")
    op.drop_table("question_attempts")
    op.drop_index("ix_mastery_book", table_name="topic_mastery")
    op.drop_table("topic_mastery")
    op.drop_index("ix_questions_fingerprint", table_name="questions")
    op.drop_index("ix_questions_bank", table_name="questions")
    op.drop_table("questions")
    op.drop_index("ix_evidence_book_chunk", table_name="evidence_references")
    op.drop_table("evidence_references")
    op.drop_index("ix_topics_book_chapter", table_name="topics")
    op.drop_table("topics")
    op.drop_index("ix_summaries_lookup", table_name="summaries")
    op.drop_table("summaries")
    op.drop_index(op.f("ix_reading_states_book_id"), table_name="reading_states")
    op.drop_table("reading_states")
    op.drop_index("ix_quiz_sessions_book", table_name="quiz_sessions")
    op.drop_table("quiz_sessions")
    op.drop_index("ix_chunks_book_chapter", table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_user_achievements_owner_user_id"), table_name="user_achievements")
    op.drop_table("user_achievements")
    op.drop_index("ix_jobs_book_type", table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_index(op.f("ix_chapters_book_id"), table_name="chapters")
    op.drop_table("chapters")
    op.drop_index("ix_annotations_book", table_name="annotations")
    op.drop_table("annotations")
    op.drop_index("ix_analytics_name_time", table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_actor_pseudo_id"), table_name="analytics_events")
    op.drop_table("analytics_events")
    op.drop_index("ix_ai_exec_created", table_name="ai_executions")
    op.drop_index("ix_ai_exec_book", table_name="ai_executions")
    op.drop_table("ai_executions")
    op.drop_index(op.f("ix_books_processing_status"), table_name="books")
    op.drop_index(op.f("ix_books_owner_user_id"), table_name="books")
    op.drop_index("ix_books_owner_hash", table_name="books")
    op.drop_index(op.f("ix_books_guest_session_id"), table_name="books")
    op.drop_table("books")
    op.drop_index(op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_index(op.f("ix_guest_sessions_secure_session_token_hash"), table_name="guest_sessions")
    op.drop_index(op.f("ix_guest_sessions_expires_at"), table_name="guest_sessions")
    op.drop_table("guest_sessions")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_token_hash"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_source_files_retention_expiry"), table_name="source_files")
    op.drop_index(op.f("ix_source_files_checksum"), table_name="source_files")
    op.drop_table("source_files")
    op.drop_table("achievements")
    # ### end Alembic commands ###
